version: "3"
services:
  api_service:
    build: .
    ports:
      - 8080:8080
    links:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $HOME/mongo:/data/db