server:
  port: 8080
spring:
  data:
    mongodb:
#      host: mongo_db
#      port: 27017
#      database: user
      uri: mongodb://mongo_db:27017/user
  application:
    name: user-service